//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsUpdateNotifier.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsUpdateNotifier.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature automatically downloads and installs the updates for the Windows Defender (updates for KB2267602). No other update will be affected by enabeling this feature..
        /// </summary>
        public static string Label_AutoInstallComment {
            get {
                return ResourceManager.GetString("Label_AutoInstallComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To automatically install the updates for the Windows Defender, the Windows Update Notifier must be setup to run as an administrator. .
        /// </summary>
        public static string Label_AutoInstallNotAvailable {
            get {
                return ResourceManager.GetString("Label_AutoInstallNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Installation.
        /// </summary>
        public static string Label_AutoInstallSettings {
            get {
                return ResourceManager.GetString("Label_AutoInstallSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Windows Defender updates automatically.
        /// </summary>
        public static string Label_AutoInstallWindowsDefenderUpdates {
            get {
                return ResourceManager.GetString("Label_AutoInstallWindowsDefenderUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Label_CommonSettings {
            get {
                return ResourceManager.GetString("Label_CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Label_Help {
            get {
                return ResourceManager.GetString("Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide trayicon when no updates are available.
        /// </summary>
        public static string Label_HideIcon {
            get {
                return ResourceManager.GetString("Label_HideIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See here, how to achieve this..
        /// </summary>
        public static string Label_HowToStartAsAdmin {
            get {
                return ResourceManager.GetString("Label_HowToStartAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes..
        /// </summary>
        public static string Label_Minutes {
            get {
                return ResourceManager.GetString("Label_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for updates every.
        /// </summary>
        public static string Label_RefreshInterval {
            get {
                return ResourceManager.GetString("Label_RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed!
        ///Start with admin privileges and try again..
        /// </summary>
        public static string Label_SavingSettingsFailed {
            get {
                return ResourceManager.GetString("Label_SavingSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Windows Update Notifier on system startup.
        /// </summary>
        public static string Label_SetAsAutoStartup {
            get {
                return ResourceManager.GetString("Label_SetAsAutoStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use metro-style for notification popup.
        /// </summary>
        public static string Label_UseMetroStyleForPopup {
            get {
                return ResourceManager.GetString("Label_UseMetroStyleForPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Notification.
        /// </summary>
        public static string Menu_DisableNotification {
            get {
                return ResourceManager.GetString("Menu_DisableNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet-Connection..
        /// </summary>
        public static string Menu_NoConnection {
            get {
                return ResourceManager.GetString("Menu_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for updates.
        /// </summary>
        public static string Menu_StartSearch {
            get {
                return ResourceManager.GetString("Menu_StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-Update Control-Panel.
        /// </summary>
        public static string Menu_WindowsUpdates {
            get {
                return ResourceManager.GetString("Menu_WindowsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open Update Panel..
        /// </summary>
        public static string Popup_ClickToOpen {
            get {
                return ResourceManager.GetString("Popup_ClickToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One update is available..
        /// </summary>
        public static string Popup_OneUpdateAvailableMessage {
            get {
                return ResourceManager.GetString("Popup_OneUpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updates are available..
        /// </summary>
        public static string Popup_UpdatesAvailableMessage {
            get {
                return ResourceManager.GetString("Popup_UpdatesAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Updates Available.
        /// </summary>
        public static string Popup_UpdatesAvailableTitle {
            get {
                return ResourceManager.GetString("Popup_UpdatesAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Windows Updates have been installed..
        /// </summary>
        public static string Popup_UpdatesInstalledMessage {
            get {
                return ResourceManager.GetString("Popup_UpdatesInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Updates Installed.
        /// </summary>
        public static string Popup_UpdatesInstalledTitle {
            get {
                return ResourceManager.GetString("Popup_UpdatesInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Connection to the WindowsUpdate-Service can&apos;t be established..
        /// </summary>
        public static string ToolTip_NoConnection {
            get {
                return ResourceManager.GetString("ToolTip_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available..
        /// </summary>
        public static string ToolTip_NothingFound {
            get {
                return ResourceManager.GetString("ToolTip_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for updates ....
        /// </summary>
        public static string ToolTip_Searching {
            get {
                return ResourceManager.GetString("ToolTip_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, a metro-style popop will be used for update notifications.
        ///Otherwise a Windows 7 like balloontip will be used..
        /// </summary>
        public static string ToolTip_UseMetroStyleForPopup {
            get {
                return ResourceManager.GetString("ToolTip_UseMetroStyleForPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update Notifier.
        /// </summary>
        public static string WindowTitle_Settings {
            get {
                return ResourceManager.GetString("WindowTitle_Settings", resourceCulture);
            }
        }
    }
}
